# Generated by Django 5.2.8 on 2026-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_estoque_preco_total_estoque_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
