# Generated by Django 5.2.8 on 2026-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
