# Generated by Django 5.2.8 on 2026-04-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendas', '0002_remove_venda_produto_remove_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
